insert into Books (Name, DateOfPublishing, Type) values ('Wild Blue Yonder, The', '1/7/2009', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Japon (a.k.a. Japan) (Japón)', '3/31/1983', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Drishyam', '1/15/1994', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Junkopia', '6/26/2002', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Subspecies IV: Bloodstorm', '7/27/1988', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Goke, Body Snatcher from Hell', '12/7/1978', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Tusk', '11/4/1978', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Unknown Pleasures (Ren xiao yao)', '11/5/2006', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Tyler Perry''s A Madea Christmas', '1/5/1987', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Zus & Zo', '8/27/1987', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Brigadoon', '3/5/1983', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Fred & Vinnie', '5/25/2010', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Debut, The', '12/27/1981', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Eddie Murphy Delirious', '11/12/1997', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Disorderlies', '9/2/1983', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('My Left Eye Sees Ghosts (Ngo joh aan gin diy gwai)', '6/1/1981', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Gurren Lagann: Childhood', '12/25/2011', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Before Sunrise', '12/9/1989', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('18 Again!', '8/18/2014', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Age of Innocence, The', '7/31/1971', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Downfall (Untergang, Der)', '3/4/1970', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('3 Blind Mice', '3/2/2014', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('September', '2/23/2007', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('She''s So Lovely', '6/20/2000', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Union Station', '2/2/1990', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Jet Lag (Décalage horaire)', '3/24/1998', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Shoes of the Fisherman, The', '10/15/2008', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Joe Versus the Volcano', '7/8/2004', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Impact', '3/23/1987', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Patlabor: The Movie', '3/28/1995', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('God is Great', '10/27/2012', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('The Golden Eye', '7/31/2000', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Walk Softly, Stranger', '4/30/2005', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Beguiled, The', '10/24/1993', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Enforcer, The', '1/19/1971', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Lost in the Desert', '3/5/2002', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Wer', '12/18/1981', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Monster, The (Mostro, Il)', '1/27/2005', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Daddy Long Legs', '6/15/1998', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Pit and the Pendulum, The', '4/29/1970', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Vääpeli Körmy ja kahtesti laukeava', '11/24/1976', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('I Bury the Living', '11/15/1969', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('a/k/a Tommy Chong', '5/20/1987', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Fat City', '8/3/1970', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Santa Clause 3: The Escape Clause, The', '11/2/2010', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Heartbreak Hospital', '12/25/1997', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Mother of Tears', '5/29/2005', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Treasure of the Sierra Madre, The', '5/21/1987', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Move Over, Darling', '11/19/1980', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('My Awkward Sexual Adventure', '10/18/1980', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Avenue Montaigne (Fauteuils d''orchestre)', '7/10/1974', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Beans of Egypt, Maine, The', '9/3/1993', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Far Cry', '10/10/1991', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Bad Eggs', '3/17/1970', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Killing of a Chinese Bookie, The', '11/8/1998', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('I Want You', '10/26/1980', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Fidanzati, I (Fiances, The)', '2/18/2010', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Seven Ways from Sundown', '11/19/2002', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Gerhard Richter Painting', '3/23/1978', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Birders: The Central)', '11/1/1986', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Affliction', '5/8/2006', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Salaam-E-Ishq', '5/10/1991', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Ito: A Diary of an Urban', '8/2/1998', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Secret World of Arrietty', '4/7/1980', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Heaven', '7/3/1989', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Not Without My Daughter', '1/23/1998', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Re-cycle (Gwai wik)', '4/15/2015', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Along the Ridge (Anche libero va bene)', '10/15/1975', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Ivanhoe', '10/13/1981', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Out of Balance', '6/22/1971', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Right Kind of Wrong, The', '12/13/1979', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Général Idi Amin Dada', '1/10/1971', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Above the Stree', '9/30/1999', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('The Inhabited Island', '12/9/1985', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Ninja Cheerleaders', '10/18/2003', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Musa the Warrior (Musa)', '8/9/2014', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Delgo', '12/19/1998', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Lady of Chance, A', '11/21/1997', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('First Sunday', '9/9/1970', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Tevye', '11/27/1972', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Horseman, The', '7/1/1966', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('Survival of the Dead', '1/9/1999', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Sound of Music, The', '7/5/2014', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Final Countdown, The', '5/18/1973', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Alvin and the Chipmunks', '8/5/2014', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Judas Kiss', '8/30/1978', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Horseman on the Roof)', '2/1/1992', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Main Hoon Na', '1/4/1968', 'strucna');
insert into Books (Name, DateOfPublishing, Type) values ('Last Run', '3/16/1974', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Comrades: Almost', '3/19/2015', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Borrowers, The', '3/3/1978', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Noi the Albino (Nói albinói)', '8/13/1984', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Five Graves to Cairo', '6/13/2006', 'znanstvena');
insert into Books (Name, DateOfPublishing, Type) values ('Latcho Drom', '10/27/2011', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Sergeant, The', '8/22/1993', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('RV', '7/28/1981', 'biografija');
insert into Books (Name, DateOfPublishing, Type) values ('A Lesson Before Dying', '9/14/1971', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Element of Crime', '11/25/2013', 'lektira');
insert into Books (Name, DateOfPublishing, Type) values ('Merry Widow, The', '5/9/2006', 'umjetnicka');
insert into Books (Name, DateOfPublishing, Type) values ('Judge, The', '5/5/1979', 'biografija');
