insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('ROBITUSSIN NIGHT TIME COUGH', 'Mira Minguet', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Lorazepam', 'Deedee Whyley', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Ifosfamide', 'Euphemia Brittlebank', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('allergy', 'Berty Scowcraft', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('ITCHY SKIN ERUPTIONS', 'Anica Pether', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('CLE DE PEAU BEAUTE FOUNDATION', 'Mycah Banford', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('RAGWITEK', 'Franklyn Di Batista', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Phenobarbital', 'Ilyse Manicomb', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('NITROUS OXIDE', 'Giovanna Brandes', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Nitrogen Oxygen Mix', 'Crista Lossman', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Haloperidol', 'Filippa Bonnell', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Cutiecaine', 'Nada Gedling', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Mango Spice Antibacterial', 'Juieta Kildahl', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Tizanidine Hydrochloride', 'Gwyn Bernardez', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Levothyroxine Sodium', 'Thorvald Langsdon', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Tree of Heaven', 'Robers Davisson', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('AZO', 'Lacey Eason', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Gold Bond Ultimate Protection', 'Hollie Beste', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('BALANCE DYNAMICS BALANCING', 'Easter Pieroni', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Risperidone', 'Dalton Garaghan', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Tusnel Pediatric', 'Abraham Ropartz', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Budesonide Inhalation', 'Niki Muldrew', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Tempra', 'Marketa Vernon', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Body', 'Storm Bilsland', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Pleo Muc', 'Marsha Plak', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Ondansetron', 'Lorilee Hunsworth', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Sodium Citrate Blood-Pack', 'Kennett Yelland', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('FLUTICASONE PROPIONATE', 'Wendye Kempster', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Glycopyrrolate', 'Merry Eagell', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Suave', 'Hynda Kewish', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Metoprolol Tartrate', 'Bryn Cust', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Aloe Up', 'Latashia McKeating', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Solmeet denti doctor', 'Falkner Grigoliis', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('MANGO BEBE LIP CARE', 'Tamara Saveall', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('COUMADIN', 'Heddie Carslaw', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Bronkisan', 'Theobald Jump', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('CEIBA PENTANDRA FIBER', 'Beitris Goroni', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('HYDROCODONE BITARTRATE', 'Maxi Trewartha', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Gabapentin', 'Rebekkah Hinchshaw', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Effexor', 'Eden Polet', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Infants Gas Relief', 'Vicky Golborn', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Prenatabs FA', 'Menard Holehouse', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('enema mineral oil', 'Haze Topling', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Citalopram', 'Lindsy Abazi', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Gabapentin', 'Paquito Leachman', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Day Time Cold/Flu Relief', 'Thatcher Andraud', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Losartan Potassium', 'Frederic Scamel', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('ReCreate Foundation', 'Noni Breslin', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('TRICOR', 'Mable Gonsalo', '7am', '7pm');
insert into Libraries (Name, Librarian, OpeningTime, ClosingTime) values ('Fast Arthritis Aid', 'Carolus Ikin', '7am', '7pm');

